name: Publish Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up UV and Python
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Cache mkdocs-materialx dependencies
        uses: actions/cache@v6
        with:
          key: mkdocs-materialx-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-materialx-
      - name: Install dependencies and deploy docs
        run: |
          uv sync --only-group docs
          uv run properdocs gh-deploy --force
